### ISSUE TITLE
[BUG] gulp dependencies are broken with 6.14.0 and old node.js (6.11.0)

### ISSUE THREAD

**Issue by coffee-lover16** [npm/cli#952]
# What / Why
Having 6.14.0 npm and old node.js versions (6.11) I can't run simple gulp task (it works with older npm versions like 6.8.0 or 6.9.0)
> 

## When
By running simple gulp task

## Where
It fails during gulp task executing (log attached)
>module.js:471
throw err;
^                                                                                                                                                                                                                                                                                                                           Error: Cannot find module 'source-map'
at Function.Module._resolveFilename (module.js:469:15)                                                                                                          at Function.Module._load (module.js:417:25)                                                                                                                     at Module.require (module.js:497:17)                                                                                                                            at require (internal/module.js:20:19)                                                                                                                           at Object.<anonymous> (C:\git\test3\node_modules\snapdragon\lib\utils.js:8:21)                                                                                  at Module._compile (module.js:570:32)                                                                                                                           at Object.Module._extensions..js (module.js:579:10)                                                                                                             at Module.load (module.js:487:32)                                                                                                                               at tryModuleLoad (module.js:446:12)                                                                                                                             at Function.Module._load (module.js:438:3) 

## How

### Current Behavior
* Running simple gulp task is failed

### Steps to Reproduce
<!-- Describe how to produce the issue -->
* Add package.json and gulp.js files (please find them in the attachment)
[npm_issue.zip](https://github.com/npm/cli/files/4258042/npm_issue.zip)
* run `npm install`
* run `npm run start`

### Expected Behavior
<!-- Describe how it should work -->
* Gulp task should be proceeded without errors

**Comment by ljharb** [comment]
The latest version of npm that works on node v6.0/v6.1 is v6.9, but as far as I know every other node 6 version works with the latest npm version.

**Comment by coffee-lover16** [comment]
@ljharb , thanks for reply! 

Is there any place/link I can refer that the latest version of npm for node.js 6.11 is v6.9? So I can close a ticket because it works as designed

**Comment by ljharb** [comment]
You misunderstand; i said node v6.0 and v6.1 - v6.*eleven* should work fine.

**Comment by coffee-lover16** [comment]
Ah, got it. I thought other then 6.1x. Thanks for clarification with that!

**Comment by leemev91** [comment]
Also encountering this issue, try lots of different things as well as trying to install source-map individually but no luck, exact same error as @Eugenio161288

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
